name: Install and Upload Release

on:
  schedule:
    - cron: "0, 0, 1, *, *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: "& ./install.ps1"
    - run: Write-Output '::set-output name=date::"${{ github.event.repository.updated_at}}".Split("T")[0]'
    - name: Package & Upload
      uses: ncipollo/release-action@v1.14.0
      with:
        name: "mpv-${{ steps.date.outputs.date }}"
        artifacts: "*"
        makeLatest: true
        omitBody: true
        skipIfReleaseExists: true
