name: Install and Upload Release

on:
  schedule:
    - cron: "0, 0, 1, *, *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get Date
      id: get-date
      run: |
        "DATE=$('${{github.event.repository.updated_at}}'.Split("T")[0])" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        Write-Host ${{ steps.get-date.outputs.DATE }}
    - name: Install
      run: "& ./install.ps1"
    - name: Package & Upload
      uses: ncipollo/release-action@v1.14.0
      with:
        name: "mpv-${{ steps.outputs.date }}"
        tag: ${{ steps.get-date.outputs.DATE }}
        artifacts: "*"
        makeLatest: true
        omitBody: true
        skipIfReleaseExists: true
